/* AI-ASSISTED: portions of this file were written with the help of an AI assistant (Claude / GPT), per course policy. */
/* Data: approximate published values. radius = atomic radius in pm (calculated/empirical), en = Pauling electronegativity (null where undefined, e.g. He, Ne, Ar), ie = first ionization energy in kJ/mol. */
const FZ_ELEMENTS = [
{z:1, sym:"H", name:"Hydrogen", row:1, col:1, radius:25, en:2.2, ie:1312, quip:"Light, flammable, and eager to start trouble."},
{z:2, sym:"He", name:"Helium", row:1, col:18, radius:31, en:null, ie:2372, quip:"It floats above the drama and never bonds."},
{z:3, sym:"Li", name:"Lithium", row:2, col:1, radius:145, en:0.98, ie:520, quip:"Soft metal with a talent for mood swings."},
{z:4, sym:"Be", name:"Beryllium", row:2, col:2, radius:105, en:1.57, ie:900, quip:"Small, stiff, and hazardous to inhale."},
{z:5, sym:"B", name:"Boron", row:2, col:13, radius:85, en:2.04, ie:801, quip:"A metalloid that keeps its options open."},
{z:6, sym:"C", name:"Carbon", row:2, col:14, radius:70, en:2.55, ie:1086, quip:"Builds diamonds, soot, and most of your problems."},
{z:7, sym:"N", name:"Nitrogen", row:2, col:15, radius:65, en:3.04, ie:1402, quip:"Quietly fills the room and judges the oxygen."},
{z:8, sym:"O", name:"Oxygen", row:2, col:16, radius:60, en:3.44, ie:1314, quip:"Supports life and several spectacular fires."},
{z:9, sym:"F", name:"Fluorine", row:2, col:17, radius:50, en:3.98, ie:1681, quip:"Takes electrons with unsettling enthusiasm."},
{z:10, sym:"Ne", name:"Neon", row:2, col:18, radius:38, en:null, ie:2081, quip:"Glows brightly while refusing to participate."},
{z:11, sym:"Na", name:"Sodium", row:3, col:1, radius:180, en:0.93, ie:496, quip:"Explodes in water and calls that chemistry."},
{z:12, sym:"Mg", name:"Magnesium", row:3, col:2, radius:150, en:1.31, ie:738, quip:"Burns brilliantly when subtlety is unavailable."},
{z:13, sym:"Al", name:"Aluminum", row:3, col:13, radius:125, en:1.61, ie:578, quip:"Lightweight, useful, and perpetually recyclable."},
{z:14, sym:"Si", name:"Silicon", row:3, col:14, radius:110, en:1.9, ie:787, quip:"Runs the modern world while pretending to be sand."},
{z:15, sym:"P", name:"Phosphorus", row:3, col:15, radius:100, en:2.19, ie:1012, quip:"Glows in the dark and hoards useful bonds."},
{z:16, sym:"S", name:"Sulfur", row:3, col:16, radius:100, en:2.58, ie:1000, quip:"Smells like bad decisions and volcanic plumbing."},
{z:17, sym:"Cl", name:"Chlorine", row:3, col:17, radius:79, en:3.16, ie:1251, quip:"Pool smell. Will take an electron from almost anyone."},
{z:18, sym:"Ar", name:"Argon", row:3, col:18, radius:71, en:null, ie:1521, quip:"Noble, inert, and content to mind its business."},
{z:19, sym:"K", name:"Potassium", row:4, col:1, radius:220, en:0.82, ie:419, quip:"Water is its least favorite place to be."},
{z:20, sym:"Ca", name:"Calcium", row:4, col:2, radius:180, en:1.0, ie:590, quip:"Builds bones and reacts before reading the instructions."},
{z:21, sym:"Sc", name:"Scandium", row:4, col:3, radius:160, en:1.36, ie:633, quip:"Rare, useful, and routinely overlooked."},
{z:22, sym:"Ti", name:"Titanium", row:4, col:4, radius:140, en:1.54, ie:659, quip:"Strong enough for planes and awkward confidence."},
{z:23, sym:"V", name:"Vanadium", row:4, col:5, radius:135, en:1.63, ie:651, quip:"Adds strength while keeping a low profile."},
{z:24, sym:"Cr", name:"Chromium", row:4, col:6, radius:140, en:1.66, ie:653, quip:"Makes steel tough and surfaces impressively shiny."},
{z:25, sym:"Mn", name:"Manganese", row:4, col:7, radius:140, en:1.55, ie:717, quip:"Essential in small doses, troublesome in large ones."},
{z:26, sym:"Fe", name:"Iron", row:4, col:8, radius:140, en:1.83, ie:763, quip:"Builds civilizations and rusts in the rain."},
{z:27, sym:"Co", name:"Cobalt", row:4, col:9, radius:135, en:1.88, ie:760, quip:"Blue pigment, battery helper, complicated reputation."},
{z:28, sym:"Ni", name:"Nickel", row:4, col:10, radius:135, en:1.91, ie:737, quip:"Resists corrosion and still gets blamed for allergies."},
{z:29, sym:"Cu", name:"Copper", row:4, col:11, radius:135, en:1.9, ie:746, quip:"Conducts electricity and ages into a green roof."},
{z:30, sym:"Zn", name:"Zinc", row:4, col:12, radius:135, en:1.65, ie:906, quip:"Protects steel and quietly supports your enzymes."},
{z:31, sym:"Ga", name:"Gallium", row:4, col:13, radius:130, en:1.81, ie:579, quip:"Melts in your hand and confuses the periodic table."},
{z:32, sym:"Ge", name:"Germanium", row:4, col:14, radius:125, en:2.01, ie:762, quip:"A semiconductor with vintage technology credentials."},
{z:33, sym:"As", name:"Arsenic", row:4, col:15, radius:115, en:2.18, ie:947, quip:"Useful in tiny amounts and regrettable in others."},
{z:34, sym:"Se", name:"Selenium", row:4, col:16, radius:115, en:2.55, ie:941, quip:"Necessary for life, but not in heroic quantities."},
{z:35, sym:"Br", name:"Bromine", row:4, col:17, radius:94, en:2.96, ie:1140, quip:"The red-brown liquid halogen nobody invites to the pool."},
{z:36, sym:"Kr", name:"Krypton", row:4, col:18, radius:88, en:3.0, ie:1351, quip:"Noble gas with a name much more dramatic than its habits."},
{z:37, sym:"Rb", name:"Rubidium", row:5, col:1, radius:235, en:0.82, ie:403, quip:"Reacts with water like it has somewhere to be."},
{z:38, sym:"Sr", name:"Strontium", row:5, col:2, radius:200, en:0.95, ie:550, quip:"Turns fireworks red and fools bones into taking it for calcium."},
{z:39, sym:"Y", name:"Yttrium", row:5, col:3, radius:180, en:1.22, ie:600, quip:"Useful in lasers, ceramics, and obscure trivia."},
{z:40, sym:"Zr", name:"Zirconium", row:5, col:4, radius:155, en:1.33, ie:640, quip:"Survives heat, corrosion, and suspiciously shiny jewelry."},
{z:41, sym:"Nb", name:"Niobium", row:5, col:5, radius:145, en:1.6, ie:652, quip:"Superconducts when sufficiently cold and patient."},
{z:42, sym:"Mo", name:"Molybdenum", row:5, col:6, radius:145, en:2.16, ie:684, quip:"Handles heat while possessing an inconvenient name."},
{z:43, sym:"Tc", name:"Technetium", row:5, col:7, radius:135, en:1.9, ie:702, quip:"Radioactive, artificial, and medically useful."},
{z:44, sym:"Ru", name:"Ruthenium", row:5, col:8, radius:130, en:2.2, ie:710, quip:"Hard, rare, and excellent at catalytic side work."},
{z:45, sym:"Rh", name:"Rhodium", row:5, col:9, radius:135, en:2.28, ie:720, quip:"Expensive enough to make a mirror nervous."},
{z:46, sym:"Pd", name:"Palladium", row:5, col:10, radius:140, en:2.2, ie:804, quip:"Absorbs hydrogen and inflates its own importance."},
{z:47, sym:"Ag", name:"Silver", row:5, col:11, radius:160, en:1.93, ie:731, quip:"Conducts magnificently and tarnishes for attention."},
{z:48, sym:"Cd", name:"Cadmium", row:5, col:12, radius:155, en:1.69, ie:868, quip:"Bright pigments, useful batteries, serious toxicity."},
{z:49, sym:"In", name:"Indium", row:5, col:13, radius:155, en:1.78, ie:558, quip:"Soft enough to complain when you bend it."},
{z:50, sym:"Sn", name:"Tin", row:5, col:14, radius:145, en:1.96, ie:709, quip:"Keeps cans useful and alloys pleasantly cooperative."},
{z:51, sym:"Sb", name:"Antimony", row:5, col:15, radius:145, en:2.05, ie:834, quip:"A brittle metalloid with an ancient reputation."},
{z:52, sym:"Te", name:"Tellurium", row:5, col:16, radius:140, en:2.1, ie:869, quip:"Rare, brittle, and mildly offensive to the nose."},
{z:53, sym:"I", name:"Iodine", row:5, col:17, radius:115, en:2.66, ie:1008, quip:"Purple vapor with a respectable medical résumé."},
{z:54, sym:"Xe", name:"Xenon", row:5, col:18, radius:108, en:2.6, ie:1170, quip:"Noble gas that occasionally agrees to make compounds."},
{z:55, sym:"Cs", name:"Cesium", row:6, col:1, radius:260, en:0.79, ie:376, quip:"Explodes eagerly and keeps very accurate time."},
{z:56, sym:"Ba", name:"Barium", row:6, col:2, radius:215, en:0.89, ie:503, quip:"Heavy, reactive, and oddly helpful with medical scans."},
{z:57, sym:"La", name:"Lanthanum", row:9, col:3, radius:195, en:1.1, ie:538, quip:"Starts the lanthanides with quiet metallic confidence."},
{z:58, sym:"Ce", name:"Cerium", row:9, col:4, radius:185, en:1.12, ie:534, quip:"Sparks from friction and takes oxidation personally."},
{z:59, sym:"Pr", name:"Praseodymium", row:9, col:5, radius:185, en:1.13, ie:527, quip:"Green glass specialist with a name to remember."},
{z:60, sym:"Nd", name:"Neodymium", row:9, col:6, radius:185, en:1.14, ie:533, quip:"Makes powerful magnets and holds grudges magnetically."},
{z:61, sym:"Pm", name:"Promethium", row:9, col:7, radius:185, en:1.13, ie:540, quip:"Radioactive and too rare for a normal introduction."},
{z:62, sym:"Sm", name:"Samarium", row:9, col:8, radius:180, en:1.17, ie:545, quip:"Magnetic, radioactive, and quietly overqualified."},
{z:63, sym:"Eu", name:"Europium", row:9, col:9, radius:185, en:1.2, ie:547, quip:"Makes red phosphors and takes names literally."},
{z:64, sym:"Gd", name:"Gadolinium", row:9, col:10, radius:180, en:1.2, ie:593, quip:"Magnetic enough to improve scans and complicate disposal."},
{z:65, sym:"Tb", name:"Terbium", row:9, col:11, radius:175, en:1.2, ie:566, quip:"Green luminescence with a stubbornly obscure name."},
{z:66, sym:"Dy", name:"Dysprosium", row:9, col:12, radius:175, en:1.22, ie:573, quip:"Magnetic and difficult, as its name openly admits."},
{z:67, sym:"Ho", name:"Holmium", row:9, col:13, radius:175, en:1.23, ie:581, quip:"Strongly magnetic and proud of its unusual hometown."},
{z:68, sym:"Er", name:"Erbium", row:9, col:14, radius:175, en:1.24, ie:589, quip:"Makes pink glass look more intentional."},
{z:69, sym:"Tm", name:"Thulium", row:9, col:15, radius:175, en:1.25, ie:597, quip:"Rare, expensive, and still waiting for a big break."},
{z:70, sym:"Yb", name:"Ytterbium", row:9, col:16, radius:175, en:1.1, ie:603, quip:"Soft lanthanide with a talent for shifting phases."},
{z:71, sym:"Lu", name:"Lutetium", row:9, col:17, radius:175, en:1.27, ie:524, quip:"The lanthanide finale arrives with expensive composure."},
{z:72, sym:"Hf", name:"Hafnium", row:6, col:4, radius:155, en:1.3, ie:658, quip:"Dense, durable, and hiding behind zirconium."},
{z:73, sym:"Ta", name:"Tantalum", row:6, col:5, radius:145, en:1.5, ie:761, quip:"Resists corrosion with almost theatrical commitment."},
{z:74, sym:"W", name:"Tungsten", row:6, col:6, radius:135, en:2.36, ie:770, quip:"The heavyweight champion of useful stubbornness."},
{z:75, sym:"Re", name:"Rhenium", row:6, col:7, radius:135, en:1.9, ie:760, quip:"Rare, dense, and comfortable near jet engines."},
{z:76, sym:"Os", name:"Osmium", row:6, col:8, radius:130, en:2.2, ie:840, quip:"Very dense and not interested in your carrying capacity."},
{z:77, sym:"Ir", name:"Iridium", row:6, col:9, radius:135, en:2.2, ie:880, quip:"Rare, corrosion-proof, and impressively unbothered."},
{z:78, sym:"Pt", name:"Platinum", row:6, col:10, radius:135, en:2.28, ie:870, quip:"Catalyzes patiently and charges accordingly."},
{z:79, sym:"Au", name:"Gold", row:6, col:11, radius:135, en:2.54, ie:890, quip:"Shiny, malleable, and aware of its market value."},
{z:80, sym:"Hg", name:"Mercury", row:6, col:12, radius:150, en:2.0, ie:1010, quip:"Liquid metal with a dangerous sense of humor."},
{z:81, sym:"Tl", name:"Thallium", row:6, col:13, radius:190, en:1.62, ie:589, quip:"Soft, poisonous, and no substitute for a handshake."},
{z:82, sym:"Pb", name:"Lead", row:6, col:14, radius:180, en:2.33, ie:716, quip:"Dense, useful, and medically uninvited."},
{z:83, sym:"Bi", name:"Bismuth", row:6, col:15, radius:160, en:2.02, ie:703, quip:"Heavy metal with unexpectedly colorful crystals."},
{z:84, sym:"Po", name:"Polonium", row:6, col:16, radius:190, en:2.0, ie:812, quip:"Radioactive enough to make secrecy seem sensible."},
{z:85, sym:"At", name:"Astatine", row:6, col:17, radius:127, en:2.2, ie:920, quip:"Rare halogen that barely has time for introductions."},
{z:86, sym:"Rn", name:"Radon", row:6, col:18, radius:120, en:2.2, ie:1037, quip:"Invisible radioactive gas with poor indoor manners."},
{z:87, sym:"Fr", name:"Francium", row:7, col:1, radius:270, en:0.7, ie:380, quip:"Extremely rare and spectacularly reactive."},
{z:88, sym:"Ra", name:"Radium", row:7, col:2, radius:215, en:0.9, ie:509, quip:"Glows historically, irradiates enthusiastically."},
{z:89, sym:"Ac", name:"Actinium", row:10, col:3, radius:195, en:1.1, ie:499, quip:"Radioactive starter of an inconvenient series."},
{z:90, sym:"Th", name:"Thorium", row:10, col:4, radius:180, en:1.3, ie:587, quip:"Heavy, radioactive, and always mentioned near reactors."},
{z:91, sym:"Pa", name:"Protactinium", row:10, col:5, radius:180, en:1.5, ie:568, quip:"Rare, radioactive, and named with high expectations."},
{z:92, sym:"U", name:"Uranium", row:10, col:6, radius:175, en:1.38, ie:598, quip:"Powerful, heavy, and rarely invited to dinner."},
{z:93, sym:"Np", name:"Neptunium", row:10, col:7, radius:175, en:1.36, ie:605, quip:"Artificially dramatic and named after a distant planet."},
{z:94, sym:"Pu", name:"Plutonium", row:10, col:8, radius:175, en:1.28, ie:585, quip:"Radioactive, complicated, and never low stakes."},
{z:95, sym:"Am", name:"Americium", row:10, col:9, radius:175, en:1.3, ie:578, quip:"Lives in smoke detectors and raises the alarm."},
{z:96, sym:"Cm", name:"Curium", row:10, col:10, radius:175, en:1.3, ie:581, quip:"Radioactive tribute to two very busy scientists."},
{z:97, sym:"Bk", name:"Berkelium", row:10, col:11, radius:170, en:1.3, ie:601, quip:"Made in tiny amounts with enormous paperwork."},
{z:98, sym:"Cf", name:"Californium", row:10, col:12, radius:170, en:1.3, ie:608, quip:"Rare neutron source with an expensive personality."},
{z:99, sym:"Es", name:"Einsteinium", row:10, col:13, radius:170, en:1.3, ie:619, quip:"Named for genius, produced in microscopic quantities."},
{z:100, sym:"Fm", name:"Fermium", row:10, col:14, radius:170, en:1.3, ie:627, quip:"A laboratory guest who leaves no measurable trace."},
{z:101, sym:"Md", name:"Mendelevium", row:10, col:15, radius:170, en:1.3, ie:635, quip:"Honors the table while refusing to stick around."},
{z:102, sym:"No", name:"Nobelium", row:10, col:16, radius:170, en:1.3, ie:642, quip:"Noble by name, fleeting by nature."},
{z:103, sym:"Lr", name:"Lawrencium", row:10, col:17, radius:170, en:1.3, ie:470, quip:"The actinide finale keeps its electron behavior mysterious."},
{z:104, sym:"Rf", name:"Rutherfordium", row:7, col:4, radius:160, en:null, ie:580, quip:"A superheavy atom with a very short appointment."},
{z:105, sym:"Db", name:"Dubnium", row:7, col:5, radius:160, en:null, ie:665, quip:"Exists briefly and still expects proper pronunciation."},
{z:106, sym:"Sg", name:"Seaborgium", row:7, col:6, radius:160, en:null, ie:740, quip:"Superheavy, synthetic, and not built for small talk."},
{z:107, sym:"Bh", name:"Bohrium", row:7, col:7, radius:160, en:null, ie:800, quip:"A fleeting metal with a distinguished namesake."},
{z:108, sym:"Hs", name:"Hassium", row:7, col:8, radius:160, en:null, ie:760, quip:"Dense in theory and temporary in practice."},
{z:109, sym:"Mt", name:"Meitnerium", row:7, col:9, radius:160, en:null, ie:840, quip:"Named for brilliance, observed only in fragments."},
{z:110, sym:"Ds", name:"Darmstadtium", row:7, col:10, radius:160, en:null, ie:950, quip:"Made atom by atom and gone almost immediately."},
{z:111, sym:"Rg", name:"Roentgenium", row:7, col:11, radius:160, en:null, ie:1020, quip:"A synthetic heavyweight with no patience for storage."},
{z:112, sym:"Cn", name:"Copernicium", row:7, col:12, radius:160, en:null, ie:1155, quip:"Volatile for a metal and cosmically named."},
{z:113, sym:"Nh", name:"Nihonium", row:7, col:13, radius:170, en:null, ie:704, quip:"Newly named, rarely seen, and chemically undecided."},
{z:114, sym:"Fl", name:"Flerovium", row:7, col:14, radius:170, en:null, ie:820, quip:"Superheavy element with surprisingly evasive chemistry."},
{z:115, sym:"Mc", name:"Moscovium", row:7, col:15, radius:170, en:null, ie:540, quip:"A short-lived guest from a very large family."},
{z:116, sym:"Lv", name:"Livermorium", row:7, col:16, radius:170, en:null, ie:663, quip:"Heavy, fleeting, and still awaiting a personality."},
{z:117, sym:"Ts", name:"Tennessine", row:7, col:17, radius:165, en:null, ie:742, quip:"A synthetic halogen with barely any free time."},
{z:118, sym:"Og", name:"Oganesson", row:7, col:18, radius:157, en:null, ie:860, quip:"The heaviest known element refuses to sit still."}
];
